# Try to find the GNU Multiple Precision Arithmetic Library (GMP)
# See http://gmplib.org/

IF(GMP_INCLUDE_DIR AND GMP_LIBRARIES)
  SET(GMP_FIND_QUIETLY TRUE)
ENDIF(GMP_INCLUDE_DIR AND GMP_LIBRARIES)

FIND_PATH(GMP_INCLUDE_DIR
  NAMES gmp.h
  PATHS $ENV{GMPDIR} ${INCLUDE_INSTALL_DIR}
)

FIND_LIBRARY(GMP_LIBRARIES gmp PATHS $ENV{GMPDIR} ${LIB_INSTALL_DIR})

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  GMP
  DEFAULT_MSG
  GMP_INCLUDE_DIR
  GMP_LIBRARIES
)

MARK_AS_ADVANCED(
  GMP_INCLUDE_DIR
  GMP_LIBRARIES
)

