INCLUDE(FindPackageHandleStandardArgs)

IF (NOT CBASE_INCLUDE_DIR)
    FIND_PATH(CBASE_INCLUDE_DIR
        NAMES cbase.h
        HINTS $ENV{CBASE_INCLUDE_DIR}
        PATH_SUFFIXES cbase
    )
ENDIF()

IF (NOT CBASE_LIBRARIES)
    FIND_LIBRARY(CBASE_LIBRARIES
        NAMES cbase
        HINTS $ENV{CBASE_LIB_DIR}
    )
ENDIF()

MARK_AS_ADVANCED(CBASE_INCLUDE_DIR)
MARK_AS_ADVANCED(CBASE_LIBRARIES)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    CBASE
    DEFAULT_MSG
    CBASE_LIBRARIES
    CBASE_INCLUDE_DIR
)

